Fix Typescript errors
Fixes the following Typescript errors:
- `src/components/ui/calendar.tsx(57,9): error TS2353: Object literal may only specify known properties, and 'icons' does not exist in type 'Partial<CustomComponents>'.`
- `src/hooks/use-admin-prompts-list.tsx(50,45): error TS2339: Property 'created_at' does not exist on type '{ id: string; name: string; }'.`
- `src/hooks/use-admin-prompts-list.tsx(121,51): error TS2339: Property 'created_at' does not exist on type '{ id: string; name: string; }'.`